### PR TITLE
[WIP] Fix #20

### LINKED ISSUE #20: require silently dropped if name of imported module is contained in the file's path
The changes made by #11 introduce the following problem:

Consider a file `tests/DFATests.hs`

```haskell
module DFATests where
require DFA
```

this drops the the import of `DFA` because `"DFA"` is *contained* in `"tests/DFATests.hs"`.

---

I stumbled upon this problem before organizing my modules hierarchically, so this isn't a real problem because the module name is to become something like `Data.Automaton.DFA` and it's quite unusual to have a path include that verbatim.

If this issue should get fixed (rather than just documented) I am willing to work on it but would like some guidance, since after looking at the discussions of #10 and #11 I'm not really sure how/why that fix works the way it does.

### PR DESCRIPTION
**Pull request by JaSpa**
Initial test case to illustrate #20.

### CODE REVIEW

**Comment by JaSpa** [comment]
@NickSeagull please take look at the second commit I added and tell me if this case should be fixed by #11, or more specifically: in which cases that fix keeps one from doing cyclic imports.

**Comment by NickSeagull** [comment]
Thanks for this! 🙏 

What is happening in #11 is that the `renderImport` function is not rendering the import (that is, writing an import to the output file) in the case that the import is a subset of the current module, hence the bug you submitted in #21 .

I think that a possible fix would be to change the `isInfixOf` condition for an exact check and make sure that nothing breaks 😁

**Comment by JaSpa** [comment]
As I see it, the test case I added in my second commit should *pass,* right? If so the check is broken in itself currently because that test *fails as well.*

But if this test case is correct to fail, I don't understand in which cases `renderImport` should render nothing.

So it would be great if you could clarify my main point of confusion, which is when *you* think the `renderImport` function should render to nothing.

**Comment by NickSeagull** [comment]
Yes, that test should pass, I'm not sure why it is failing. As you understood correctly, the `renderImport` should only render nothing in the case that the module that it is going to import, and the current module are the same one, else, it will render it properly.

**Comment by JaSpa** [comment]
This was subsumed by #22.

**Pull request closed without merging**
